@URL=http://localhost:5220/api

@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJlbWFpbCI6InBlZHJvQGdtYWlsLmNvbSIsIm5iZiI6MTcxOTYxNjkxNiwiZXhwIjoxNzIyMjA4OTE2LCJpYXQiOjE3MTk2MTY5MTZ9.RHRFhsQ3JOuO2DIuCV850oFWkB_tX1SO-s2KbRaN63E

### Get All Categories
GET {{URL}}/Categories/
Authorization: {{JWT}}


### Get All Expenses Categories
GET {{URL}}/Categories/Expenses
Authorization: {{JWT}}


### Get All Income Categories
GET {{URL}}/Categories/Income
Authorization: {{JWT}}

