@URL=http://localhost:5220/api

@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJlbWFpbCI6InBlZHJvQGdtYWlsLmNvbSIsIm5iZiI6MTcxOTYxNjkxNiwiZXhwIjoxNzIyMjA4OTE2LCJpYXQiOjE3MTk2MTY5MTZ9.RHRFhsQ3JOuO2DIuCV850oFWkB_tX1SO-s2KbRaN63E

### Add a Transaction
POST {{URL}}/Transaction/
Content-Type: application/json
Authorization: {{JWT}}

{
   "description": "Electric Bill",
   "value": 5.0,
   "type": "I",
   "date": "2023-04-10",
   "categoryID": 3
}

### Get All Transactions
GET {{URL}}/Transaction/
Authorization: {{JWT}}

### Get One Transactions
GET {{URL}}/Transaction/11
Authorization: {{JWT}}


### Get All Income
GET {{URL}}/Transaction/Income
Authorization: {{JWT}}


### Get All Expenses
GET {{URL}}/Transaction/Expenses
Authorization: {{JWT}}


### Get All Transactions by category
GET {{URL}}/Transaction/Category/3
Authorization: {{JWT}}


### Update a Transaction
PATCH {{URL}}/Transaction/
Content-Type: application/json
Authorization: {{JWT}}

{
   "transactionID": 12,
   "description": "Electric Bill2",
   "value": 15.0,
   "type": "I",
   "date": "2023-04-11",
   "fkCategory": 3
}


### Delete a Transaction by Id
DELETE {{URL}}/Transaction/12
Authorization: {{JWT}}
