@URL=https://localhost:5001/api

@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJlbWFpbCI6InBlZHJvQGdtYWlsLmNvbSIsIm5iZiI6MTY4NjUwMzU0OCwiZXhwIjoxNjg5MDk1NTQ4LCJpYXQiOjE2ODY1MDM1NDh9.u2FJuJ983lopBIzZ6CdhBqa9dSI-xoXlfohl9zY-pgA

### Register a User
POST {{URL}}/User/register
Content-Type: application/json

{
	"name": "Pedro J de O",
	"lastName": "Sawczuk",
	"email": "pedro@gmail.com",
	"password": "1234"
}


### Login (Generate Token)
POST  {{URL}}/User/login
Content-Type: application/json

{
	"email": "pedro@gmail.com",
	"password": "1234"
}


### Get User by token
GET  {{URL}}/User/verify
Authorization: {{JWT}}


### Atualizar um usuário
PATCH {{URL}}/User/
Content-Type: application/json
Authorization: {{JWT}}

{
   "userID": "4",
   "name": "Juca",
	"lastName": "Silva",
   "email": "juca4@gmail.com",
   "password": "12345"
}


### Deletar um usuário
DELETE {{URL}}/User/
Authorization: {{JWT}}