@URL=http://localhost:5220/api

@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJlbWFpbCI6InBlZHJvQGdtYWlsLmNvbSIsIm5iZiI6MTcxOTYxNjkxNiwiZXhwIjoxNzIyMjA4OTE2LCJpYXQiOjE3MTk2MTY5MTZ9.RHRFhsQ3JOuO2DIuCV850oFWkB_tX1SO-s2KbRaN63E

### Register a User
POST {{URL}}/User/register
Content-Type: application/json

{
	"name": "Pedro J de O",
	"lastName": "Sawczuk",
	"email": "pedro@gmail.com",
	"password": "1234"
}


### Login (Generate Token)
POST  {{URL}}/User/login
Content-Type: application/json

{
	"email": "pedro@gmail.com",
	"password": "1234"
}


### Verify User by token
GET  {{URL}}/User/verify
Authorization: {{JWT}}


### Atualizar um usuário
PATCH {{URL}}/User/
Content-Type: application/json
Authorization: {{JWT}}

{
   "userID": "4",
   "name": "Juca",
	"lastName": "Silva",
   "email": "juca4@gmail.com",
   "password": "12345"
}


### Deletar um usuário
DELETE {{URL}}/User/
Authorization: {{JWT}}