@URL=https://localhost:5001/api

@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUiLCJlbWFpbCI6InBlZHJvQGdtYWlsLmNvbSIsIm5iZiI6MTY4NjI1ODM1MSwiZXhwIjoxNjg4ODUwMzUxLCJpYXQiOjE2ODYyNTgzNTF9.pMF0lEpfVXGVFPL0d5d70EMCO8FzTwMCtBJBFz1AUEo

### Add a Transaction
POST {{URL}}/Transaction/
Content-Type: application/json
Authorization: {{JWT}}

{
    "description": "Electric Bill",
    "value": 5.0,
    "type": "D",
    "date": "2023-04-10",
    "fkCategory": 3
}

### Get All Transactions
GET {{URL}}/Transaction/
Authorization: {{JWT}}


### Get All Earnings
GET {{URL}}/Transaction/Earnings
Authorization: {{JWT}}


### Get All Expenses
GET {{URL}}/Transaction/Expenses
Authorization: {{JWT}}


### Update a Transaction
PATCH {{URL}}/Transaction/
Content-Type: application/json
Authorization: {{JWT}}

{
    "transactionID": 11,
    "description": "Electric Bill2",
    "value": 15.0,
    "type": "D",
    "date": "2023-04-11",
    "fkCategory": 3
}


### Delete a Transaction by Id
DELETE {{URL}}/Transaction/4
Authorization: {{JWT}}


### Get All Transactions by category
GET {{URL}}/Transaction/
Content-Type: application/json
Authorization: {{JWT}}

{
    "fkCategory": 3
}